version: '3.8'
services:
  stock-management:
    build: ./stock-management
    ports:
      - "8000:8000"
  comptabilite:
    build: ./comptabilite
    ports:
      - "8001:80"
  authentification:
    build: ./authentification
    ports:
      - "8002:80"